FROM python:3.11-slim

WORKDIR /app

# Install required packages
RUN pip install --no-cache-dir kafka-python psycopg2-binary

# Copy the consumer script
COPY ./scripts/kafka-consumer.py .

CMD ["python", "-u", "kafka-consumer.py"]